# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:3.11

stages:
  - build
  - test
  - upload
  - release

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PACKAGE_REGISTRY_PYPI_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi/simple"
  PACKAGE_REGISTRY_GENERIC_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic"

# https://pip.pypa.io/en/stable/topics/caching/
cache:
  paths:
    - .cache/pip


build-job:
  stage: build
  before_script:
    - python --version ; pip --version  # For debugging
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
  script:
    - pip install build
    - python -m build --wheel
    - echo "WHEELFILE=`ls dist`" > wheel.env
  artifacts:
    paths:
      - dist/DiSQ*.whl
    reports: 
      dotenv: wheel.env

test-install-job:
  stage: test
  before_script:
    - python --version ; pip --version  # For debugging
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
  script:
    - pip install -e .[dev]
    # run the command here

upload-generic-job:
  stage: upload
  image: curlimages/curl:latest
  rules:
    - if: $CI_COMMIT_TAG
  needs:
    - job: build-job
      artifacts: true
  cache: []
  before_script:
    - echo "VERSION=${CI_COMMIT_TAG}" > version.env
    - echo "WHEELFILE=${WHEELFILE}" >> version.env
  script:
    - |
      echo "Package registry url: ${PACKAGE_REGISTRY_GENERIC_URL}"
      echo "wheelfile: ${WHEELFILE}"
      ls dist/
      curl -s --fail-with-body --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file dist/${WHEELFILE} ${PACKAGE_REGISTRY_GENERIC_URL}/DiSQ/${WHEELFILE}
  artifacts:
    reports:
      dotenv: version.env


release-job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
   - if: $CI_COMMIT_TAG                 # Run this job when a tag is created
  needs:
    - job: upload-generic-job
      artifacts: true
  cache: []
  script:
    - echo "running release_job"
  release:                               # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
    tag_name: '${CI_COMMIT_TAG}'
    description: 'Release ${CI_COMMIT_TAG} TESTING CI'
    ref: '${CI_COMMIT_SHA}'
    assets:
      links:
        - name: '${WHEELFILE}'
          url: '${PACKAGE_REGISTRY_GENERIC_URL}/DiSQ/${WHEELFILE}'
          #filepath: '/disq/${WHEELFILE}' # optional
          link_type: 'package' # optional
