image: $SKA_K8S_TOOLS_DOCKER_BUILDER_IMAGE

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  CI_POETRY_VERSION: 1.8.2

stages:
  - lint
  - build
  - test
  - scan
  - publish
  - pages

include:
  # Python packages build,lint, test and publish
  - project: "ska-telescope/templates-repository"
    file: "gitlab-ci/includes/python.gitlab-ci.yml"

  # Jupyter Notebooks
  - project: "ska-telescope/templates-repository"
    file: "gitlab-ci/includes/notebook.gitlab-ci.yml"

  # Docs pages
  - project: "ska-telescope/templates-repository"
    file: "gitlab-ci/includes/docs.gitlab-ci.yml"

  # Build and publish changelog
  - project: "ska-telescope/templates-repository"
    file: "gitlab-ci/includes/release.gitlab-ci.yml"

  # Create Gitlab CI badges from CI metrics
  - project: "ska-telescope/templates-repository"
    file: "gitlab-ci/includes/finaliser.gitlab-ci.yml"

notebook-lint:
  when: manual

notebook-test:
  when: manual

python-test:
  image: registry.gitlab.com/ska-telescope/ska-mid-dish-qualification/ci-tests:latest
  script:
    - make python-test PYTHON_VARS_BEFORE_PYTEST=xvfb-run
