[tool.poetry]
name = "ska-mid-dish-qualification"
version = "0.2.1"
description = "SKA-Mid Dish Structure Qualification (DiSQ) software"
authors = [
    "Oliver Skivington <oliver.skivington@criticalsoftware.com>",
    "Thomas Juerges <thomas.juerges@skao.int>",
    "Ulrik Pedersen <ukp@observatorysciences.co.uk>",
]
license = "BSD-3-Clause"
readme = "README.md"
homepage = "https://gitlab.com/ska-telescope/ska-mid-dish-qualification"

[tool.poetry.scripts]
disq-gui = "ska_mid_dish_qualification.mvcmain:main"
disq-validate-server = "ska_mid_dish_qualification.server_validator:main"

[[tool.poetry.source]]
name = 'ska'
url = 'https://artefact.skatelescope.org/repository/pypi-all/simple'

[tool.poetry.urls]
"Bug Tracker" = "https://gitlab.com/ska-telescope/ska-mid-dish-qualification/-/issues"

[tool.poetry.dependencies]
python = "^3.10"
asyncua = "^1.0.0"
PyQt6 = "^6.4.0"
pyqt6-tools = "^6.4.0"
python-dotenv = "^1.0.0"
# matplotlib and plotly are only used in the reader class.
matplotlib = "^3.8.0"
plotly = "^5.18.0"
pyyaml = "^6.0.0"
h5py = "^3.10.0"
numpy = "^1.26.0"

[tool.poetry.group.dev.dependencies]
pytest = ">=6.2.5,<7.0.0"
pytest-cov = "^4.0.0"
assertpy = "^1.1"
isort = "^5.10.1"
black = "^22.10.0"
pylint = "^2.15.5"
pylint-junit = "^0.3.2"
flake8 = "^5.0.4"
flake8-isort = "^6.1.0"
flake8-formatter-junit-xml = "^0.0.6"
flake8-builtins = "^1.5.3"
flake8-docstrings = "^1.6.0"
flake8-use-fstring = "^1.4"
flake8-rst-docstrings = "^0.2.7"
mypy = "^1.4.1"
pep8-naming = "^0.13.1"

[tool.poetry.group.docs.dependencies]
Sphinx = "^5.2"
docutils = "^0.17"
sphinx-argparse = "^0.3"
ska-ser-sphinx-theme = "^0.1.1"
sphinx-autodoc-typehints = "^1.19"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.setuptools_scm]
write_to = "src/ska_mid_dish_qualification/_version.py"

[tool.mypy]
ignore_missing_imports = true # Ignore missing stubs in imported modules

[tool.isort]
float_to_top = true
profile = "black"

[tool.black] # See https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#configuration-format
force-exclude = "src/ska_mid_dish_qualification/sculib.py" # RegEx - Exclude formatting the legacy code

[tool.pytest.ini_options]
# Run pytest with all our checkers, and don't spam us with massive tracebacks on error
addopts = """
    --tb=native -vv --doctest-modules --doctest-glob="*.rst"
    """
# https://iscinumpy.gitlab.io/post/bound-version-constraints/#watch-for-warnings
filterwarnings = "error"
# Doctest python code in docs, python code in src docstrings, test functions in tests
testpaths = "docs src tests"

[tool.coverage.run]
data_file = "/tmp/ska_mid_dish_qualification.coverage"

[tool.coverage.paths]
# Tests are run from installed location, map back to the src directory
source = ["src", "**/site-packages/"]
