[build-system]
requires = ["setuptools>=64", "setuptools_scm[toml]>=6.2", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "DiSQ"
classifiers = [
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: BSD 3-Clause License",
    "Programming Language :: Python :: 3.10",
]
description = "SKA-Mid Dish Structure Qualification (DiSQ) software"
dependencies = [
    "asyncua",
    "PyQt6==6.4.2",
    "pyqt6-tools",
    "python-dotenv",
    "h5py",
    "numpy",
    # matplotlib and plotly are only used in the reader class.
    "matplotlib",
    "plotly",
    "pyyaml",
    "platformdirs",
]

dynamic = ["version"]
license.file = "LICENSE"
readme = "README.md"
requires-python = ">=3.10"

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
    "assertpy",
    "isort",
    "black",
    "pylint",
    "pylint-junit",
    "flake8",
    "flake8-isort",
    "flake8-formatter-junit-xml",
    "flake8-builtins",
    "flake8-docstrings",
    "flake8-use-fstring",
    "flake8-rst-docstrings",
    "mypy",
    "pep8-naming",
    "build",
    "Sphinx",
    "sphinx-argparse",
    "ska-ser-sphinx-theme @ git+https://gitlab.com/ska-telescope/ska-ser-sphinx-theme.git@0.1.2",
    "sphinx-autodoc-typehints",
    "nbqa",
]

[project.scripts]
disq-gui = "disq.mvcmain:main"
disq-validate-server = "disq.server_validator:main"

[project.urls]
GitLab = "https://gitlab.com/ska-telescope/ska-mid-dish-qualification"
source = "https://gitlab.com/ska-telescope/ska-mid-dish-qualification"

[[project.authors]] # Further authors may be added by duplicating this section
email = "Thomas.Juerges@skao.int"
name = "Thomas Juerges"
[[project.authors]]
email = "oliver.skivington@criticalsoftware.com"
name = "Oliver Skivington"
[[project.authors]]
email = "ukp@observatorysciences.co.uk"
name = "Ulrik Pedersen"

[tool.poetry]
include = ["MANIFEST.skao.int"]
name = "DiSQ"
version = "0.2.1"
description = "SKA-Mid Dish Structure Qualification (DiSQ) software"
authors = [
    "Oliver Skivington <oliver.skivington@criticalsoftware.com>",
    "Thomas Juerges <thomas.juerges@skao.int>",
    "Ulrik Pedersen <ukp@observatorysciences.co.uk>",
]
license = "BSD-3-Clause"
readme = "README.md"
repository = "https://gitlab.com/ska-telescope/ska-mid-dish-qualification"
documentation = "https://developer.skatelescope.org/projects/ska-mid-dish-qualification"

[tool.poetry.scripts]
disq-gui = "disq.mvcmain:main"
disq-validate-server = "disq.server_validator:main"

[[tool.poetry.source]]
name = "ska"
url = "https://artefact.skatelescope.org/repository/pypi-internal/simple"
priority = "supplemental"

[tool.poetry.dependencies]
python = "^3.10"
asyncua = "^1.0.0"
PyQt6 = "^6.4.0"
pyqt6-tools = "^6.4.0"
python-dotenv = "^1.0.0"
# matplotlib and plotly are only used in the reader class.
matplotlib = "^3.8.0"
plotly = "^5.18.0"
pyyaml = "^6.0.0"
h5py = "^3.10.0"
numpy = "^1.26.0"
platformdirs = "^4.2.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.1.1"
pytest-cov = "^4.0.0"
assertpy = "^1.1"
isort = "^5.13.2"
black = "^24.2.0"
pylint = "^3.1.0"
pylint-junit = "^0.3.2"
flake8 = "^7.0.0"
flake8-formatter-junit-xml = "^0.0.6"
flake8-builtins = "^2.1.0"
flake8-docstrings = "^1.7.0"
flake8-use-fstring = "^1.4"
flake8-rst-docstrings = "^0.3.0"
mypy = "^1.9.0"
pep8-naming = "^0.13.3"
build = "^1.1.1"
nbqa = "^1.8.4"

[tool.poetry.group.docs.dependencies]
Sphinx = "^7.2.6"
sphinx-autodoc-typehints = "^2.0.0"
ska-ser-sphinx-theme = "^0.1.2"
sphinx-argparse = "^0.4.0"

[tool.setuptools_scm]
write_to = "src/disq/_version.py"

[tool.mypy]
ignore_missing_imports = true # Ignore missing stubs in imported modules

[tool.isort]
profile = "black"

[tool.black] # See https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#configuration-format
force-exclude = "src/disq/sculib.py|src/disq/_version.py" # RegEx - Exclude formatting the legacy code
line-length = 88

[tool.pytest.ini_options]
# Run pytest with all our checkers, and don't spam us with massive tracebacks on error
addopts = """
    --tb=native -v --doctest-modules --doctest-glob="*.rst"
    """
# https://iscinumpy.gitlab.io/post/bound-version-constraints/#watch-for-warnings
filterwarnings = "error"
# Doctest python code in docs, python code in src docstrings, test functions in tests
testpaths = "docs src tests"

[tool.coverage.run]
omit = ["__init__.py", "_version.py"]

[tool.coverage.paths]
# Tests are run from installed location, map back to the src directory
source = ["src", "**/site-packages/"]
