version: 1
disable_existing_loggers: true

formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  error:
    format: "%(asctime)s - %(filename)012s:%(lineno)d - %(levelname)s %(name)s: %(message)s"
  debug:
    format: "%(asctime)s %(filename)012s:%(lineno)4d - %(name)12s - %(levelname)7s %(funcName)s(): %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout

  file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: /tmp/info.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

root:
  level: NOTSET
  handlers: [console]
  propogate: no

loggers:
  asyncua:
    level: WARNING
    handlers: []
    propogate: no

  sculib:
    level: INFO
    handlers: []
    propogate: no

  gui:
    level: INFO
    handlers: []
    propogate: no

  datalog:
    level: INFO
    handlers: []
    propogate: no
