version: 1
disable_existing_loggers: true

formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  error:
    format: "%(asctime)s - %(filename)014s:%(lineno)d - %(levelname)s %(name)s: %(message)s"
  debug:
    format: "%(asctime)s %(filename)014s:%(lineno)04d %(name)12s %(levelname)7s: %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout

  file_handler:
    class: logging.handlers.TimedRotatingFileHandler
    level: DEBUG
    formatter: debug
    filename: "logs/disq.log"
    atTime: "08:00:00"
    # when: "h"
    # maxBytes: 1048576 # 1MB
    backupCount: 20
    encoding: utf8
    utc: True

root:
  level: NOTSET
  handlers: [console, file_handler]
  propogate: no

loggers:
  asyncua:
    level: WARNING
    handlers: []
    propogate: no

  ska-mid-ds-scu:
    level: INFO
    handlers: []
    propogate: no

  gui:
    level: INFO
    handlers: []
    propogate: no

  datalog:
    level: INFO
    handlers: []
    propogate: no
